### ISSUE TITLE
.Values.server.service.type ClusterIP is not supported - work only with NodePort type

### ISSUE THREAD

**Issue by abdennour** [gocd/helm-chart#8]
hi all. 
when i deploy the gocd helm chart to our kubernetes cluster the server pod hits a PostStartHookError with url: (7) Failed to connect to localhost port 8153: Connection refused.
 We're specifying a ClusterIP service type so i believe it shouldn't be trying to reach localhost?

This is my values file:

```yaml
server:
  service:
    type: "ClusterIP"
```
